/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedGuardrailsRouteImport } from './routes/_authenticated/guardrails'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as ApiPublicHooksFunnelEventRouteImport } from './routes/api/public/hooks/funnel-event'
import { Route as ApiPublicHooksComputeKpisRouteImport } from './routes/api/public/hooks/compute-kpis'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuardrailsRoute = AuthenticatedGuardrailsRouteImport.update({
  id: '/guardrails',
  path: '/guardrails',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksFunnelEventRoute =
  ApiPublicHooksFunnelEventRouteImport.update({
    id: '/api/public/hooks/funnel-event',
    path: '/api/public/hooks/funnel-event',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksComputeKpisRoute =
  ApiPublicHooksComputeKpisRouteImport.update({
    id: '/api/public/hooks/compute-kpis',
    path: '/api/public/hooks/compute-kpis',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/guardrails': typeof AuthenticatedGuardrailsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/api/public/hooks/compute-kpis': typeof ApiPublicHooksComputeKpisRoute
  '/api/public/hooks/funnel-event': typeof ApiPublicHooksFunnelEventRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/guardrails': typeof AuthenticatedGuardrailsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/hooks/compute-kpis': typeof ApiPublicHooksComputeKpisRoute
  '/api/public/hooks/funnel-event': typeof ApiPublicHooksFunnelEventRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/guardrails': typeof AuthenticatedGuardrailsRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/hooks/compute-kpis': typeof ApiPublicHooksComputeKpisRoute
  '/api/public/hooks/funnel-event': typeof ApiPublicHooksFunnelEventRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agents'
    | '/audit'
    | '/guardrails'
    | '/inventory'
    | '/api/public/hooks/compute-kpis'
    | '/api/public/hooks/funnel-event'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/agents'
    | '/audit'
    | '/guardrails'
    | '/inventory'
    | '/'
    | '/api/public/hooks/compute-kpis'
    | '/api/public/hooks/funnel-event'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agents'
    | '/_authenticated/audit'
    | '/_authenticated/guardrails'
    | '/_authenticated/inventory'
    | '/_authenticated/'
    | '/api/public/hooks/compute-kpis'
    | '/api/public/hooks/funnel-event'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksComputeKpisRoute: typeof ApiPublicHooksComputeKpisRoute
  ApiPublicHooksFunnelEventRoute: typeof ApiPublicHooksFunnelEventRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guardrails': {
      id: '/_authenticated/guardrails'
      path: '/guardrails'
      fullPath: '/guardrails'
      preLoaderRoute: typeof AuthenticatedGuardrailsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/funnel-event': {
      id: '/api/public/hooks/funnel-event'
      path: '/api/public/hooks/funnel-event'
      fullPath: '/api/public/hooks/funnel-event'
      preLoaderRoute: typeof ApiPublicHooksFunnelEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/compute-kpis': {
      id: '/api/public/hooks/compute-kpis'
      path: '/api/public/hooks/compute-kpis'
      fullPath: '/api/public/hooks/compute-kpis'
      preLoaderRoute: typeof ApiPublicHooksComputeKpisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedGuardrailsRoute: typeof AuthenticatedGuardrailsRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedGuardrailsRoute: AuthenticatedGuardrailsRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksComputeKpisRoute: ApiPublicHooksComputeKpisRoute,
  ApiPublicHooksFunnelEventRoute: ApiPublicHooksFunnelEventRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
